# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adReason',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FloatingAd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeAd', models.CharField(choices=[('V', 'VIDEO AD'), ('F', 'FLOATING CARD ADS ')], max_length=1)),
                ('time', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=400)),
                ('img', models.CharField(max_length=300)),
                ('ad_reason_cheked', models.BooleanField(default=False)),
                ('ad_removed', models.BooleanField(default=False)),
                ('reasons', models.ManyToManyField(to='StoreToDB.adReason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='hostingVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=40)),
                ('nbr_views', models.CharField(max_length=30)),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_link', models.CharField(max_length=200)),
                ('channel_img', models.CharField(max_length=500)),
                ('channel_description', models.CharField(max_length=1000)),
                ('nbr_followers', models.CharField(max_length=50)),
                ('channel_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=191, unique=True)),
                ('user_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('videos', models.ManyToManyField(to='StoreToDB.hostingVideo')),
            ],
        ),
        migrations.CreateModel(
            name='videoAd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeAd', models.CharField(choices=[('V', 'VIDEO AD'), ('F', 'FLOATING CARD ADS ')], max_length=1)),
                ('time', models.DateField()),
                ('link', models.CharField(max_length=400)),
                ('advertiser_name', models.CharField(max_length=100)),
                ('ad_channel_description', models.CharField(max_length=1000)),
                ('ad_channel_name', models.CharField(max_length=100)),
                ('ad_channel_link', models.CharField(max_length=200)),
                ('ad_channel_img', models.CharField(max_length=400)),
                ('ad_page_img', models.CharField(max_length=400)),
                ('ad_page_desctiption', models.CharField(max_length=1000)),
                ('ad_page_link', models.CharField(max_length=200)),
                ('skeept_or_not', models.BooleanField(default=False)),
                ('checked_or_not', models.BooleanField(default=False)),
                ('reason_cheked', models.BooleanField(default=False)),
                ('reasons', models.ManyToManyField(to='StoreToDB.adReason')),
                ('users', models.ManyToManyField(to='StoreToDB.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='floatingad',
            name='users',
            field=models.ManyToManyField(to='StoreToDB.user'),
        ),
    ]
