# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreToDB', '0002_auto_20200214_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adreason',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='floatingad',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostingvideo',
            name='channel_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoad',
            name='ad_channel_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videoad',
            name='ad_page_desctiption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
