# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-14 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreToDB', '0003_auto_20200214_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostingvideo',
            name='channel_checked',
        ),
        migrations.AddField(
            model_name='videoad',
            name='channel_checked',
            field=models.BooleanField(default=False),
        ),
    ]
