# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-14 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreToDB', '0004_auto_20200214_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoad',
            old_name='checked_or_not',
            new_name='ad_skeept_or_not',
        ),
        migrations.RenameField(
            model_name='videoad',
            old_name='skeept_or_not',
            new_name='advertiser_checked_or_not',
        ),
    ]
