# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-18 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreToDB', '0005_auto_20200214_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floatingad',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
