# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-18 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreToDB', '0006_auto_20200218_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floatingad',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
